language: node_js
node_js:
  - 13
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-frontend cdcongminh/udagram-frontend
  - docker tag reverseproxy cdcongminh/reverseproxy
  - docker tag udagram-api-feed cdcongminh/udagram-api-feed
  - docker tag udagram-api-user cdcongminh/udagram-api-user

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cdcongminh/udagram-frontend
  - docker push cdcongminh/reverseproxy
  - docker push cdcongminh/udagram-api-feed
  - docker push cdcongminh/udagram-api-user
